name = "tangle"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[durable_objects.bindings]]
name = "MATCHMAKER"
class_name = "Matchmaker"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Matchmaker"]

[[d1_databases]]
binding = "DB"
database_name = "tangle-db"
database_id = "6eb58b66-72dd-45ad-8e2c-d05a79023983"

[[kv_namespaces]]
binding = "KV"
id = "c3f048d469864179b4b20a29d9fb5727"

[vars]
ENVIRONMENT = "development"
DANGER_ZONE_ENABLED = "false"

[[routes]]
pattern = "tangle.saradsingh.com.np"
custom_domain = true

[assets]
directory = "./frontend/out"

[dev]
port = 8787
