ALTER TABLE players ADD COLUMN xp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN total_wins INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN title TEXT NOT NULL DEFAULT 'Apprentice';
